Document: lod2demo
Title: Debian lod2demo Manual
Author: <insert document author here>
Abstract: This manual describes what lod2demo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lod2demo/lod2demo.sgml.gz

Format: postscript
Files: /usr/share/doc/lod2demo/lod2demo.ps.gz

Format: text
Files: /usr/share/doc/lod2demo/lod2demo.text.gz

Format: HTML
Index: /usr/share/doc/lod2demo/html/index.html
Files: /usr/share/doc/lod2demo/html/*.html
