Document: testarch
Title: Debian testarch Manual
Author: <insert document author here>
Abstract: This manual describes what testarch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/testarch/testarch.sgml.gz

Format: postscript
Files: /usr/share/doc/testarch/testarch.ps.gz

Format: text
Files: /usr/share/doc/testarch/testarch.text.gz

Format: HTML
Index: /usr/share/doc/testarch/html/index.html
Files: /usr/share/doc/testarch/html/*.html
