Document: lod2statworkbench
Title: Debian lod2statworkbench Manual
Author: <insert document author here>
Abstract: This manual describes what lod2statworkbench is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lod2statworkbench/lod2statworkbench.sgml.gz

Format: postscript
Files: /usr/share/doc/lod2statworkbench/lod2statworkbench.ps.gz

Format: text
Files: /usr/share/doc/lod2statworkbench/lod2statworkbench.text.gz

Format: HTML
Index: /usr/share/doc/lod2statworkbench/html/index.html
Files: /usr/share/doc/lod2statworkbench/html/*.html
