Document: valiant
Title: Debian valiant Manual
Author: <insert document author here>
Abstract: This manual describes what valiant is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/valiant/valiant.sgml.gz

Format: postscript
Files: /usr/share/doc/valiant/valiant.ps.gz

Format: text
Files: /usr/share/doc/valiant/valiant.text.gz

Format: HTML
Index: /usr/share/doc/valiant/html/index.html
Files: /usr/share/doc/valiant/html/*.html
