#!/bin/sh
# postinst script for lod2demo
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)

	### VIRTUOSO CONFIG
	virtetc="/etc/virtuoso-opensource-6.1/"
	virtvar="/var/lib/virtuoso-opensource-6.1/"
	virtuosoini="$virtetc/virtuoso.ini"

	# stop the server
	sudo service virtuoso-opensource-6.1 stop

	# add ontowiki directory to DirsAllowed
	# try to remove the addition first in order to avoid double entries
	sed 's/^\(DirsAllowed.*\)\(, \/var\/share\/lod2demo\)\(.*\)/\1\3/' -i $virtuosoini
	sed 's/^\(DirsAllowed.*\)/\1, \/var\/share\/lod2demo/' -i $virtuosoini

	# restart the server
	sudo service virtuoso-opensource-6.1 start

	.isql-vt 1111 dba dba /var/share/lod2demo/load.sql
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#
echo "---- ending postinst $@"

exit 0
